(function(){'use strict';
  const {canvas}=ImageFilters;
  function aperture(ctx,shape,x,y,r,rotation){const sides=shape==='octagon'?8:shape==='diamond'?4:shape==='triangle'?3:0;ctx.beginPath();if(!sides){ctx.arc(x,y,r,0,Math.PI*2);return}const start=rotation*Math.PI/180-Math.PI/2;for(let i=0;i<sides;i++){const a=start+i*Math.PI*2/sides,px=x+Math.cos(a)*r,py=y+Math.sin(a)*r;i?ctx.lineTo(px,py):ctx.moveTo(px,py)}ctx.closePath()}
  function saturate(r,g,b,amount){const gray=.299*r+.587*g+.114*b,f=Math.max(0,amount)/100;return[gray+(r-gray)*f,gray+(g-gray)*f,gray+(b-gray)*f]}
  function apply(source,opt,quality='full'){if(!opt||!opt.enabled||Number(opt.radius)<=0)return source;const w=source.width,h=source.height,short=Math.min(w,h),radius=Math.max(.1,Number(opt.radius)||1),fx=(Number(opt.focusX)||.5)*w,fy=(Number(opt.focusY)||.5)*h,focusR=Math.max(.01,Number(opt.focusRadius)||.24)*short,transition=Math.max(.01,Number(opt.transition)||.18)*short;
    const blurred=canvas(w,h),bctx=blurred.getContext('2d');bctx.filter=`blur(${Math.min(60,radius)}px)`;bctx.drawImage(source,0,0);bctx.filter='none';
    const out=canvas(w,h),ctx=out.getContext('2d');ctx.drawImage(blurred,0,0);
    const focus=canvas(w,h),fctx=focus.getContext('2d');fctx.drawImage(source,0,0);fctx.globalCompositeOperation='destination-in';const mask=fctx.createRadialGradient(fx,fy,Math.max(0,focusR-transition),fx,fy,focusR+transition);mask.addColorStop(0,'rgba(0,0,0,1)');mask.addColorStop(.48,'rgba(0,0,0,.98)');mask.addColorStop(1,'rgba(0,0,0,0)');fctx.fillStyle=mask;fctx.fillRect(0,0,w,h);ctx.drawImage(focus,0,0);
    const opacity=Math.max(0,Math.min(1,Number(opt.opacity)||0)),density=Math.max(1,Math.min(100,Number(opt.density)||1)),threshold=Math.max(0,Math.min(1,(Number(opt.threshold)||0)/100));if(opacity<=0)return out;
    const sampleMax=quality==='fast'?170:260,scale=Math.min(1,sampleMax/Math.max(w,h)),sw=Math.max(1,Math.round(w*scale)),sh=Math.max(1,Math.round(h*scale)),sample=canvas(sw,sh),sctx=sample.getContext('2d',{willReadFrequently:true});sctx.drawImage(source,0,0,sw,sh);const data=sctx.getImageData(0,0,sw,sh).data,step=Math.max(1,Math.round(Math.sqrt(sw*sh/(quality==='fast'?6000:14000)))),points=[];
    for(let sy=0;sy<sh;sy+=step)for(let sx=0;sx<sw;sx+=step){const x=sx/sw*w,y=sy/sh*h,dx=x-fx,dy=y-fy;if(Math.hypot(dx,dy)<focusR)continue;const i=(sy*sw+sx)*4,r=data[i],g=data[i+1],b=data[i+2],lum=(.2126*r+.7152*g+.0722*b)/255;if(lum<threshold)continue;const hash=(((sx*73856093)^(sy*19349663))>>>0)%100;if(hash>density)continue;points.push({x,y,r,g,b,lum})}
    points.sort((a,b)=>b.lum-a.lum);const limit=Math.min(points.length,Math.round((quality==='fast'?55:110)+density*(quality==='fast'?1.7:3.2))),layer=canvas(w,h),lctx=layer.getContext('2d'),size=Math.max(1,Number(opt.size)||radius*1.5),light=Math.max(0,Number(opt.lightness)||0)/100,soft=Math.max(0,Number(opt.softness)||0)/100,rotation=Number(opt.rotation)||0,saturation=Number(opt.saturation)||100,shape=opt.shape||'circle';
    for(let i=0;i<limit;i++){const p=points[i],strength=Math.min(1,(p.lum-threshold)/Math.max(.05,1-threshold)),[r,g,b]=saturate(p.r,p.g,p.b,saturation),alpha=opacity*strength*(.18+light*.7),rr=size*(.5+strength*.7);lctx.fillStyle=`rgba(${r|0},${g|0},${b|0},${alpha*.62})`;aperture(lctx,shape,p.x,p.y,rr,rotation);lctx.fill()}
    let softLayer=layer;if(soft>.02){softLayer=canvas(w,h);const sl=softLayer.getContext('2d');sl.filter=`blur(${Math.min(30,size*soft*.4)}px)`;sl.drawImage(layer,0,0);sl.filter='none'}ctx.save();ctx.globalCompositeOperation='lighter';if(softLayer!==layer){ctx.globalAlpha=.78;ctx.drawImage(softLayer,0,0)}ctx.globalAlpha=.72;ctx.drawImage(layer,0,0);ctx.restore();return out}
  window.ImageLensBlur={apply};
}());
