(function(){'use strict';
  class PreviewPipeline{
    constructor(canvas,onBusy,onStatus){this.canvas=canvas;this.onBusy=onBusy||(()=>{});this.onStatus=onStatus||(()=>{});this.source=null;this.state=null;this.timer=0;this.token=0;this.display={width:1,height:1};this.back=document.createElement('canvas')}
    setSource(source,state){this.source=source;this.state=state;this.updateDimensions(true)}
    setState(state){this.state=state}
    updateDimensions(force=false){if(!this.state)return;const crop=this.state.crop,ratio=Math.min(1,1200/Math.max(crop.width,crop.height)),w=Math.max(1,Math.round(crop.width*ratio)),h=Math.max(1,Math.round(crop.height*ratio));if(force||w!==this.display.width||h!==this.display.height){this.display={width:w,height:h};this.canvas.width=w;this.canvas.height=h;this.back.width=w;this.back.height=h}}
    schedule(mode='fast',delay){clearTimeout(this.timer);this.timer=setTimeout(()=>this.render(mode),delay==null?(mode==='fast'?42:12):delay)}
    async render(mode='full'){if(!this.source||!this.state)return;const token=++this.token;this.updateDimensions();const heavy=this.state.lens.enabled||this.state.grain.amount>0||this.state.filters.motionBlur>0||this.state.sharpness.amount>0,max=mode==='fast'&&heavy?620:mode==='fast'?900:1200,ratio=Math.min(1,max/Math.max(this.state.crop.width,this.state.crop.height)),pw=Math.max(1,Math.round(this.state.crop.width*ratio)),ph=Math.max(1,Math.round(this.state.crop.height*ratio));this.onBusy(true);this.onStatus(mode==='fast'?'Vista previa rápida…':'Procesando vista previa…');await new Promise(r=>requestAnimationFrame(r));if(token!==this.token)return;try{const rendered=ImageRenderer.render(this.source,this.state,{width:pw,height:ph,quality:mode});if(token!==this.token)return;const bctx=this.back.getContext('2d');bctx.clearRect(0,0,this.back.width,this.back.height);bctx.imageSmoothingEnabled=true;bctx.imageSmoothingQuality='high';bctx.drawImage(rendered,0,0,this.back.width,this.back.height);const ctx=this.canvas.getContext('2d');ctx.clearRect(0,0,this.canvas.width,this.canvas.height);ctx.drawImage(this.back,0,0);this.onStatus(`${mode==='fast'?'Preview rápida':'Preview completa'} · ${this.canvas.width} × ${this.canvas.height}px`)}catch(error){console.error(error);this.onStatus('Error al procesar la vista previa')}finally{if(token===this.token)this.onBusy(false)}}
  }
  window.ImagePreviewPipeline={PreviewPipeline};
}());
