(function(){'use strict';
  const groups={
    adjustments:[['Brillo','adjustments.brightness',-100,100,1,''],['Contraste','adjustments.contrast',-100,100,1,''],['Saturación','adjustments.saturation',-100,100,1,''],['Exposición','adjustments.exposure',-100,100,1,''],['Temperatura','adjustments.temperature',-100,100,1,''],['Matiz','adjustments.hue',-180,180,1,'°'],['Vibrance','adjustments.vibrance',-100,100,1,''],['Gamma','adjustments.gamma',.1,3,.05,''],['Sombras','adjustments.shadows',-100,100,1,''],['Iluminaciones','adjustments.highlights',-100,100,1,''],['Blancos','adjustments.whites',-100,100,1,''],['Negros','adjustments.blacks',-100,100,1,''],['Escala grises','filters.grayscale',0,100,1,'%'],['Monocromo','filters.monochrome',0,100,1,'%'],['Sepia','filters.sepia',0,100,1,'%'],['Invertir','filters.invert',0,100,1,'%']],
    filters:[['Nitidez','sharpness.amount',0,100,1,'%'],['Radio nitidez','sharpness.radius',.5,8,.1,'px'],['Umbral','sharpness.threshold',0,50,1,''],['Blur gaussiano','filters.gaussianBlur',0,40,.5,'px'],['Desenfoque','filters.blur',0,40,.5,'px'],['Motion blur','filters.motionBlur',0,80,1,'px'],['Ángulo motion','filters.motionAngle',-180,180,1,'°'],['Pixelar','filters.pixelate',1,80,1,'px'],['Viñeta','filters.vignette',0,100,1,'%'],['Tamaño viñeta','filters.vignetteSize',5,95,1,'%'],['Suavidad viñeta','filters.vignetteSoftness',5,100,1,'%']],
    grain:[['Intensidad','grain.amount',0,100,1,'%'],['Tamaño','grain.size',1,12,1,'px'],['Opacidad','grain.opacity',0,1,.01,'']],
    lens:[['Radio blur','lens.radius',0,50,.5,'px'],['Luminosidad','lens.lightness',0,100,1,'%'],['Opacidad bokeh','lens.opacity',0,1,.01,''],['Tamaño bokeh','lens.size',1,80,1,'px'],['Umbral luces','lens.threshold',0,100,1,'%'],['Suavidad','lens.softness',0,100,1,'%'],['Rotación','lens.rotation',-180,180,1,'°'],['Densidad','lens.density',1,100,1,'%'],['Color / satur.','lens.saturation',0,200,1,'%'],['Radio foco','lens.focusRadius',.03,.7,.01,''],['Transición foco','lens.transition',.01,.5,.01,'']]
  };
  function get(obj,path){return path.split('.').reduce((v,k)=>v[k],obj)}function set(obj,path,value){const p=path.split('.'),k=p.pop(),target=p.reduce((v,n)=>v[n],obj);target[k]=value}
  function fmt(v,suffix,step){const d=String(step).includes('.')?Math.min(2,String(step).split('.')[1].length):0;return`${Number(v).toFixed(d)}${suffix}`}
  function build(container,state,onInput,onCommit){container.innerHTML='';const key=container.dataset.group,defs=groups[key]||[];defs.forEach(def=>{const[label,path,min,max,step,suffix]=def,row=document.createElement('label');row.className='range-row';row.innerHTML=`<span>${label}</span><input type="range" min="${min}" max="${max}" step="${step}" data-path="${path}"><output></output>`;const input=row.querySelector('input'),output=row.querySelector('output');input.value=get(state,path);output.textContent=fmt(input.value,suffix,step);input.addEventListener('input',()=>{set(state,path,Number(input.value));output.textContent=fmt(input.value,suffix,step);onInput(path)});input.addEventListener('change',()=>onCommit(path));container.appendChild(row)})}
  function sync(state){document.querySelectorAll('[data-path]').forEach(input=>{const path=input.dataset.path;input.value=get(state,path);const def=Object.values(groups).flat().find(x=>x[1]===path);if(def)input.parentElement.querySelector('output').textContent=fmt(input.value,def[5],def[4])})}
  window.ImageUI={groups,get,set,build,sync};
}());
