(function(){
'use strict';
const $=s=>document.querySelector(s);let kind='all',studio='all',query='',toastTimer=null;
const labels={silhouette:'Silueta',text:'Texto',image:'Imagen',light:'Light Lab','3d':'3D Lighting'};
function toast(message){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').classList.add('show');toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2200)}
function date(ts){try{return new Intl.DateTimeFormat('es-PE',{dateStyle:'short',timeStyle:'short'}).format(new Date(ts))}catch(_){return''}}
function safeFileName(name){return String(name||'proyecto').normalize('NFKD').replace(/[^\w\-]+/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'').slice(0,80)||'proyecto'}
function studioUrl(name){return window.StudioBridge.studioUrl(name)}
async function openRecord(record){window.StudioGallery.setLaunchIntent(record.id,record.studio);location.href=studioUrl(record.studio)}
async function exportRecord(record){const portable=await StudioGallery.toPortable(record);const blob=new Blob([JSON.stringify(portable,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${safeFileName(record.name)}.${record.studio==='text'?'tes':record.studio==='image'?'ims':record.studio==='light'?'lls':record.studio==='3d'?'k3d':'sis'}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1200);toast('Proyecto exportado.');}
function card(record){const el=document.createElement('article');el.className='gallery-card';const placeholder=record.studio==='text'?'Tt':record.studio==='image'?'\u25EB':record.studio==='light'?'\u2726':record.studio==='3d'?'3D':'\u25C6';el.innerHTML=`<div class="thumb">${record.thumbnail?'<img alt="">':`<div class="thumb-placeholder">${placeholder}</div>`}<div class="badges"><span class="badge">${labels[record.studio]}</span><span class="badge kind">${record.kind==='template'?'PLANTILLA':'DISEÑO'}</span></div></div><div class="card-body"><div class="card-name"></div><div class="card-date">Editado ${date(record.updatedAt)}</div><div class="card-actions"><button class="open">${record.kind==='template'?'Usar':'Abrir'}</button><button class="duplicate">Duplicar</button><button class="more" aria-label="Más acciones">⋯</button></div><div class="more-menu"><button class="rename">Renombrar</button><button class="export">Exportar</button><button class="delete">Eliminar</button></div></div>`;
if(record.thumbnail)el.querySelector('.thumb img').src=record.thumbnail;el.querySelector('.card-name').textContent=record.name;el.querySelector('.open').onclick=()=>openRecord(record);el.querySelector('.duplicate').onclick=async()=>{await StudioGallery.duplicate(record.id);toast('Copia creada.');render()};el.querySelector('.more').onclick=()=>el.classList.toggle('menu-open');el.querySelector('.rename').onclick=async()=>{const name=prompt('Nuevo nombre:',record.name);if(!name)return;await StudioGallery.rename(record.id,name);render()};el.querySelector('.export').onclick=()=>exportRecord(record);el.querySelector('.delete').onclick=async()=>{if(!confirm(`¿Eliminar “${record.name}”?`))return;await StudioGallery.remove(record.id);toast('Elemento eliminado.');render()};return el}
async function render(){const records=await StudioGallery.list();const filtered=records.filter(r=>kind==='all'||r.kind===kind).filter(r=>studio==='all'||r.studio===studio).filter(r=>!query||r.name.toLocaleLowerCase().includes(query));const grid=$('#galleryGrid');grid.innerHTML='';filtered.forEach(r=>grid.appendChild(card(r)));$('#emptyState').hidden=filtered.length!==0;$('#countLabel').textContent=`${filtered.length} ${filtered.length===1?'elemento':'elementos'}`}
$('#kindFilters').onclick=e=>{const b=e.target.closest('[data-kind]');if(!b)return;kind=b.dataset.kind;document.querySelectorAll('[data-kind]').forEach(x=>x.classList.toggle('active',x===b));render()};
$('#studioFilters').onclick=e=>{const b=e.target.closest('[data-studio-filter]');if(!b)return;studio=b.dataset.studioFilter;document.querySelectorAll('[data-studio-filter]').forEach(x=>x.classList.toggle('active',x===b));render()};
$('#searchInput').oninput=e=>{query=e.target.value.trim().toLocaleLowerCase();render()};
$('#importBtn').onclick=()=>$('#importInput').click();$('#importInput').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{const data=JSON.parse(await file.text());await StudioGallery.importPortable(data);toast('Proyecto importado a la galería.');render()}catch(error){console.error(error);toast(error.message||'No se pudo importar el proyecto.')}};
render();
}());
