import { projectorFromEffect } from '../../shared/lightPatterns.js?cache=projector-quality-v1-20260906';
import { EXTRA_LIGHTING_ATMOSPHERES } from '../../shared/extraLightingAtmospheres.js?cache=extra-light-presets-v1-20260907';

export const THREE_ATMOSPHERES = [
  ...EXTRA_LIGHTING_ATMOSPHERES,
  {
    id:'day',
    name:'D\u00eda',
    description:'Claro y natural.',
    scene:{
      background:'#8CBED7',
      fog:'#8CBED7',
      floor:'#7F8274',
      exposure:1.12,
      weather:'clear'
    },
    lighting:{
      ambient:{color:'#CDE6F3',intensity:24},
      shadow:{color:'#4D5868',intensity:24},
      bounce:{color:'#E4C49A',intensity:16},
      rim:{color:'#EAF7FF',intensity:10},
      key:{color:'#FFF1C9',intensity:88,azimuth:38,elevation:52,distance:5.2,softness:56},
      fill:{color:'#A8D4EE',intensity:26,azimuth:-58,elevation:20,distance:5.8,softness:78}
    }
  },
  {
    id:'dawn',
    name:'Amanecer',
    description:'Rosa suave y luz baja.',
    scene:{
      background:'#8B6E83',
      fog:'#8B6E83',
      floor:'#695B58',
      exposure:1.04,
      weather:'clear'
    },
    lighting:{
      ambient:{color:'#A88BA6',intensity:20},
      shadow:{color:'#4D3D55',intensity:34},
      bounce:{color:'#E89376',intensity:24},
      rim:{color:'#FFD7BD',intensity:14},
      key:{color:'#FFB18D',intensity:72,azimuth:-62,elevation:12,distance:5.5,softness:64},
      fill:{color:'#B7A8C8',intensity:18,azimuth:52,elevation:18,distance:6,softness:82}
    }
  },
  {
    id:'afternoon',
    name:'Tarde',
    description:'Dorada y lateral.',
    scene:{
      background:'#6D99A8',
      fog:'#6D99A8',
      floor:'#7B6950',
      exposure:1.08,
      weather:'clear'
    },
    lighting:{
      ambient:{color:'#A8C3CD',intensity:18},
      shadow:{color:'#514A4B',intensity:32},
      bounce:{color:'#DFA45E',intensity:22},
      rim:{color:'#FFE8B9',intensity:8},
      key:{color:'#FFD06E',intensity:94,azimuth:-72,elevation:24,distance:5.2,softness:42},
      fill:{color:'#9FC3D5',intensity:20,azimuth:54,elevation:15,distance:6.2,softness:76}
    }
  },
  {
    id:'sunset',
    name:'Atardecer',
    description:'Naranja y violeta.',
    scene:{
      background:'#583A52',
      fog:'#583A52',
      floor:'#4B3134',
      exposure:1.02,
      weather:'clear'
    },
    lighting:{
      ambient:{color:'#755A82',intensity:18},
      shadow:{color:'#2D2036',intensity:48},
      bounce:{color:'#D76C52',intensity:24},
      rim:{color:'#FFB879',intensity:18},
      key:{color:'#FF8F53',intensity:90,azimuth:-56,elevation:14,distance:5.3,softness:46},
      fill:{color:'#6C7DDB',intensity:36,azimuth:64,elevation:28,distance:5.8,softness:62}
    }
  },
  {
    id:'night',
    name:'Noche',
    description:'Azul profundo.',
    scene:{
      background:'#081426',
      fog:'#081426',
      floor:'#111B27',
      exposure:.88,
      weather:'night'
    },
    lighting:{
      ambient:{color:'#193C6A',intensity:22},
      shadow:{color:'#090F21',intensity:58},
      bounce:{color:'#2E5378',intensity:8},
      rim:{color:'#9EDFFF',intensity:26},
      key:{color:'#7DBAFF',intensity:56,azimuth:42,elevation:58,distance:5.3,softness:54},
      fill:{color:'#31558B',intensity:16,azimuth:-52,elevation:14,distance:6.2,softness:84}
    }
  },
  {
    id:'moon',
    name:'Luna',
    description:'Fr\u00edo con contraluz.',
    scene:{
      background:'#050C19',
      fog:'#050C19',
      floor:'#11151D',
      exposure:.82,
      weather:'moon'
    },
    lighting:{
      ambient:{color:'#182A4C',intensity:14},
      shadow:{color:'#060A14',intensity:68},
      bounce:{color:'#223B56',intensity:6},
      rim:{color:'#CDEBFF',intensity:68},
      key:{color:'#A8D7FF',intensity:32,azimuth:168,elevation:48,distance:5.8,softness:46},
      fill:{color:'#385777',intensity:12,azimuth:-34,elevation:12,distance:6.4,softness:84}
    }
  },
  {
    id:'cloudy',
    name:'Nublado',
    description:'Suave y desaturado.',
    scene:{
      background:'#89969D',
      fog:'#89969D',
      floor:'#737A78',
      exposure:.98,
      weather:'cloudy'
    },
    lighting:{
      ambient:{color:'#B1BDC2',intensity:30},
      shadow:{color:'#5D666B',intensity:26},
      bounce:{color:'#AEB8B4',intensity:14},
      rim:{color:'#DBE2E3',intensity:6},
      key:{color:'#DDE4E4',intensity:48,azimuth:8,elevation:64,distance:5.4,softness:90},
      fill:{color:'#BFC9CA',intensity:28,azimuth:-60,elevation:30,distance:6.2,softness:94}
    }
  },
  {
    id:'rain',
    name:'Lluvia',
    description:'Fr\u00edo, gris y h\u00famedo.',
    scene:{
      background:'#445A68',
      fog:'#526873',
      floor:'#3F4D4E',
      exposure:.90,
      weather:'rain'
    },
    lighting:{
      ambient:{color:'#607B89',intensity:24},
      shadow:{color:'#273640',intensity:46},
      bounce:{color:'#56757D',intensity:10},
      rim:{color:'#A6D9E7',intensity:16},
      key:{color:'#A9D5E4',intensity:44,azimuth:26,elevation:68,distance:5.6,softness:86},
      fill:{color:'#6D8D99',intensity:18,azimuth:-58,elevation:18,distance:6.2,softness:90}
    }
  },
  {
    id:'storm',
    name:'Tormenta',
    description:'Oscuro y dram\u00e1tico.',
    scene:{
      background:'#141E2E',
      fog:'#1C2A3B',
      floor:'#252B2E',
      exposure:.82,
      weather:'storm'
    },
    lighting:{
      ambient:{color:'#324D6A',intensity:14},
      shadow:{color:'#0E1522',intensity:70},
      bounce:{color:'#35516A',intensity:6},
      rim:{color:'#C7E9FF',intensity:34},
      key:{color:'#C0E8FF',intensity:86,azimuth:-46,elevation:70,distance:5.2,softness:18},
      fill:{color:'#435E7B',intensity:12,azimuth:70,elevation:22,distance:6.2,softness:74}
    }
  },
  {
    id:'fog',
    name:'Niebla',
    description:'Bajo contraste y aire gris.',
    scene:{
      background:'#A8B0B1',
      fog:'#BDC3C2',
      floor:'#858A87',
      exposure:.96,
      fogNear:5,
      fogFar:18,
      weather:'fog'
    },
    lighting:{
      ambient:{color:'#C1C8C6',intensity:36},
      shadow:{color:'#747C7D',intensity:18},
      bounce:{color:'#C5C8C3',intensity:20},
      rim:{color:'#E3E6E3',intensity:8},
      key:{color:'#E2E5DF',intensity:38,azimuth:-10,elevation:56,distance:5.5,softness:96},
      fill:{color:'#C9CDCA',intensity:26,azimuth:54,elevation:28,distance:6,softness:96}
    }
  },
  {
    id:'warm-room',
    name:'Interior c\u00e1lido',
    description:'Luz amarilla de habitaci\u00f3n.',
    scene:{
      background:'#4B332A',
      fog:'#4B332A',
      floor:'#5D4638',
      exposure:1.00,
      weather:'indoor'
    },
    lighting:{
      ambient:{color:'#745647',intensity:24},
      shadow:{color:'#302124',intensity:44},
      bounce:{color:'#D38A52',intensity:24},
      rim:{color:'#F2B777',intensity:8},
      key:{color:'#FFC46E',intensity:72,azimuth:-38,elevation:30,distance:5.2,softness:62},
      fill:{color:'#A56B4A',intensity:18,azimuth:56,elevation:16,distance:6.2,softness:82}
    }
  }
,
  {
    id:'sun-side',
    group:'creative',
    name:'Sol lateral',
    description:'Luz dorada fuerte desde un costado.',
    scene:{
      background:'#54453C',
      fog:'#54453C',
      floor:'#4D4039',
      exposure:1.12,
      weather:'clear',
      effect:{
        type:'glow',
        colorA:'#FFD56F',
        colorB:'#FF8B4A',
        opacity:24,
        angle:-28,
        scale:120
      }
    },
    lighting:{
      ambient:{color:'#8B6F68',intensity:18},
      shadow:{color:'#3B2945',intensity:46},
      bounce:{color:'#D97A45',intensity:24},
      rim:{color:'#FFE1A6',intensity:18},
      key:{color:'#FFD36E',intensity:118,azimuth:-68,elevation:30,distance:5.0,softness:36},
      fill:{color:'#8E6FA8',intensity:20,azimuth:64,elevation:18,distance:6.0,softness:76},
      extra:[
        {id:'sun-rim',name:'Rim dorado',color:'#FF9A3D',intensity:52,azimuth:158,elevation:34,distance:5.8,softness:52}
      ]
    }
  },
  {
    id:'leaf-light',
    group:'creative',
    name:'Hojas',
    description:'Manchas verdes y amarillas como luz entre hojas.',
    scene:{
      background:'#334136',
      fog:'#334136',
      floor:'#2C372E',
      exposure:.98,
      weather:'clear',
      effect:{
        type:'leaves',
        colorA:'#F2E95B',
        colorB:'#7EA94C',
        opacity:34,
        angle:-18,
        scale:110
      }
    },
    lighting:{
      ambient:{color:'#6F8061',intensity:24},
      shadow:{color:'#24322A',intensity:52},
      bounce:{color:'#7FA05A',intensity:20},
      rim:{color:'#D8E674',intensity:16},
      key:{color:'#F4E45D',intensity:96,azimuth:-32,elevation:62,distance:5.2,softness:28},
      fill:{color:'#78A66A',intensity:34,azimuth:68,elevation:24,distance:6.0,softness:68},
      extra:[
        {id:'leaf-warm',name:'Destello hoja',color:'#FFC54D',intensity:38,azimuth:-88,elevation:18,distance:5.6,softness:34}
      ]
    }
  },
  {
    id:'cool-blue',
    group:'creative',
    name:'Azul frio',
    description:'Azul celeste con sombras violetas.',
    scene:{
      background:'#172642',
      fog:'#172642',
      floor:'#1B2740',
      exposure:.92,
      weather:'clear',
      effect:{
        type:'glow',
        colorA:'#67E8F9',
        colorB:'#5B6CFF',
        opacity:26,
        angle:34,
        scale:130
      }
    },
    lighting:{
      ambient:{color:'#365A88',intensity:28},
      shadow:{color:'#251B49',intensity:56},
      bounce:{color:'#487DD1',intensity:18},
      rim:{color:'#74F0FF',intensity:28},
      key:{color:'#75DFFF',intensity:76,azimuth:42,elevation:50,distance:5.2,softness:58},
      fill:{color:'#6670FF',intensity:38,azimuth:-66,elevation:22,distance:5.9,softness:72}
    }
  },
  {
    id:'golden-rim',
    group:'creative',
    name:'Amanecer brillante',
    description:'Contraluz amarillo intenso y sombra profunda.',
    scene:{
      background:'#4A382E',
      fog:'#4A382E',
      floor:'#3B302C',
      exposure:1.08,
      weather:'clear',
      effect:{
        type:'rim',
        colorA:'#FFD000',
        colorB:'#FF6B1A',
        opacity:36,
        angle:-70,
        scale:120
      }
    },
    lighting:{
      ambient:{color:'#6A5148',intensity:18},
      shadow:{color:'#291D35',intensity:62},
      bounce:{color:'#B95A2C',intensity:18},
      rim:{color:'#FFD21A',intensity:52},
      key:{color:'#FFD21A',intensity:128,azimuth:-122,elevation:28,distance:5.2,softness:24},
      fill:{color:'#684C8F',intensity:20,azimuth:48,elevation:14,distance:6.2,softness:80},
      extra:[
        {id:'orange-edge',name:'Borde naranja',color:'#FF761F',intensity:64,azimuth:168,elevation:38,distance:5.6,softness:36}
      ]
    }
  },
  {
    id:'pink-lavender',
    group:'creative',
    name:'Rosa lavanda',
    description:'Iluminacion rosa suave con violeta.',
    scene:{
      background:'#563954',
      fog:'#563954',
      floor:'#493144',
      exposure:1.02,
      weather:'clear',
      effect:{
        type:'glow',
        colorA:'#FF8AD8',
        colorB:'#A879FF',
        opacity:28,
        angle:20,
        scale:135
      }
    },
    lighting:{
      ambient:{color:'#8A648D',intensity:28},
      shadow:{color:'#45265B',intensity:42},
      bounce:{color:'#D468B3',intensity:24},
      rim:{color:'#D6A0FF',intensity:20},
      key:{color:'#FF91D8',intensity:72,azimuth:-30,elevation:42,distance:5.2,softness:70},
      fill:{color:'#A77BFF',intensity:44,azimuth:58,elevation:28,distance:5.8,softness:74}
    }
  },
  {
    id:'yellow-stripe',
    group:'creative',
    name:'Franja amarilla',
    description:'Base morada con una franja vertical amarilla.',
    scene:{
      background:'#291A43',
      fog:'#291A43',
      floor:'#241737',
      exposure:.92,
      weather:'clear',
      effect:{
        type:'stripe',
        colorA:'#FFE866',
        colorB:'#6E3CA5',
        opacity:62,
        angle:3,
        scale:82
      }
    },
    lighting:{
      ambient:{color:'#50306F',intensity:28},
      shadow:{color:'#1E112E',intensity:64},
      bounce:{color:'#6A3D9B',intensity:18},
      rim:{color:'#C980FF',intensity:24},
      key:{color:'#FFE45A',intensity:104,azimuth:-8,elevation:56,distance:5.0,softness:16},
      fill:{color:'#7A42C3',intensity:38,azimuth:72,elevation:22,distance:6.0,softness:70}
    }
  },
  {
    id:'window-cross',
    group:'creative',
    name:'Ventana',
    description:'Luz calida atravesada por marco de ventana.',
    scene:{
      background:'#573B34',
      fog:'#573B34',
      floor:'#49352F',
      exposure:1.04,
      weather:'clear',
      effect:{
        type:'window',
        colorA:'#FFD39A',
        colorB:'#5C332E',
        opacity:46,
        angle:-4,
        scale:118
      }
    },
    lighting:{
      ambient:{color:'#7B594F',intensity:24},
      shadow:{color:'#3B282C',intensity:46},
      bounce:{color:'#CC744B',intensity:24},
      rim:{color:'#FFD1A2',intensity:12},
      key:{color:'#FFC77C',intensity:96,azimuth:-36,elevation:44,distance:5.2,softness:34},
      fill:{color:'#8C5361',intensity:20,azimuth:58,elevation:20,distance:6.0,softness:80}
    }
  },
  {
    id:'violet-orange',
    group:'creative',
    name:'Violeta y naranja',
    description:'Dos colores opuestos para un retrato dramatico.',
    scene:{
      background:'#2B183D',
      fog:'#2B183D',
      floor:'#28192F',
      exposure:.96,
      weather:'clear',
      effect:{
        type:'split',
        colorA:'#FF5D2F',
        colorB:'#5A2A93',
        opacity:34,
        angle:90,
        scale:110
      }
    },
    lighting:{
      ambient:{color:'#4A2C62',intensity:20},
      shadow:{color:'#21142F',intensity:60},
      bounce:{color:'#A43B56',intensity:18},
      rim:{color:'#FF8A4C',intensity:22},
      key:{color:'#FF6333',intensity:92,azimuth:-66,elevation:34,distance:5.2,softness:42},
      fill:{color:'#7D42D6',intensity:72,azimuth:64,elevation:28,distance:5.6,softness:50}
    }
  },
  {
    id:'olive-crimson',
    group:'creative',
    name:'Oliva y carmesi',
    description:'Verde oliva a un lado y rojo profundo al otro.',
    scene:{
      background:'#303226',
      fog:'#303226',
      floor:'#2B2924',
      exposure:.94,
      weather:'clear',
      effect:{
        type:'split',
        colorA:'#C4C95A',
        colorB:'#B63A32',
        opacity:30,
        angle:84,
        scale:110
      }
    },
    lighting:{
      ambient:{color:'#6E7048',intensity:22},
      shadow:{color:'#2B2328',intensity:52},
      bounce:{color:'#7D7E42',intensity:18},
      rim:{color:'#D45B47',intensity:20},
      key:{color:'#C7CB5D',intensity:74,azimuth:-52,elevation:42,distance:5.2,softness:54},
      fill:{color:'#C74338',intensity:68,azimuth:66,elevation:30,distance:5.6,softness:50}
    }
  },
  {
    id:'forest-lowkey',
    group:'creative',
    name:'Bosque oscuro',
    description:'Verde profundo con luz baja y reflejos amarillos.',
    scene:{
      background:'#142720',
      fog:'#142720',
      floor:'#17231D',
      exposure:.80,
      weather:'clear',
      effect:{
        type:'leaves',
        colorA:'#9CAB43',
        colorB:'#356147',
        opacity:22,
        angle:16,
        scale:145
      }
    },
    lighting:{
      ambient:{color:'#2C4E42',intensity:18},
      shadow:{color:'#0F1918',intensity:72},
      bounce:{color:'#53683A',intensity:14},
      rim:{color:'#8DBD67',intensity:16},
      key:{color:'#AAB94F',intensity:48,azimuth:-38,elevation:52,distance:5.2,softness:62},
      fill:{color:'#2F7B68',intensity:28,azimuth:70,elevation:24,distance:6.0,softness:78}
    }
  },
  {
    id:'neon-red-cyan',
    group:'creative',
    name:'Neon rojo y cian',
    description:'Rojo de un lado y cian electrico del otro.',
    scene:{
      background:'#151127',
      fog:'#151127',
      floor:'#171326',
      exposure:.92,
      weather:'clear',
      effect:{
        type:'neon',
        colorA:'#FF3C24',
        colorB:'#20E7FF',
        opacity:40,
        angle:90,
        scale:110
      }
    },
    lighting:{
      ambient:{color:'#36275B',intensity:20},
      shadow:{color:'#120C23',intensity:70},
      bounce:{color:'#A32243',intensity:16},
      rim:{color:'#39EAFF',intensity:34},
      key:{color:'#FF3B22',intensity:104,azimuth:-70,elevation:30,distance:5.0,softness:34},
      fill:{color:'#19E8FF',intensity:108,azimuth:70,elevation:34,distance:5.0,softness:34},
      extra:[
        {id:'neon-purple',name:'Rim violeta',color:'#8B3DFF',intensity:42,azimuth:168,elevation:46,distance:5.8,softness:48}
      ]
    }
  },
  {
    id:'warm-blinds',
    group:'creative',
    name:'Persianas',
    description:'Franjas horizontales de luz calida.',
    scene:{
      background:'#594038',
      fog:'#594038',
      floor:'#4A3832',
      exposure:1.02,
      weather:'clear',
      effect:{
        type:'blinds',
        colorA:'#FFD49B',
        colorB:'#5B332D',
        opacity:50,
        angle:-7,
        scale:88
      }
    },
    lighting:{
      ambient:{color:'#806056',intensity:24},
      shadow:{color:'#39282B',intensity:48},
      bounce:{color:'#CC774F',intensity:22},
      rim:{color:'#F7C191',intensity:10},
      key:{color:'#FFD093',intensity:92,azimuth:-32,elevation:46,distance:5.2,softness:34},
      fill:{color:'#8A5960',intensity:22,azimuth:60,elevation:18,distance:6.0,softness:80}
    }
  },
  {
    id:'iridescent',
    group:'creative',
    name:'Iridiscente',
    description:'Reflejos rosa, cian y violeta.',
    scene:{
      background:'#23172A',
      fog:'#23172A',
      floor:'#211923',
      exposure:.94,
      weather:'clear',
      effect:{
        type:'iridescent',
        colorA:'#FF4FA3',
        colorB:'#5DEBFF',
        opacity:32,
        angle:24,
        scale:135
      }
    },
    lighting:{
      ambient:{color:'#4A2C54',intensity:24},
      shadow:{color:'#1C1224',intensity:58},
      bounce:{color:'#CE3F8F',intensity:20},
      rim:{color:'#66ECFF',intensity:38},
      key:{color:'#FF4FA3',intensity:76,azimuth:-52,elevation:38,distance:5.2,softness:48},
      fill:{color:'#5DEBFF',intensity:72,azimuth:62,elevation:34,distance:5.4,softness:48},
      extra:[
        {id:'iri-violet',name:'Violeta',color:'#8F5BFF',intensity:42,azimuth:160,elevation:52,distance:5.8,softness:52}
      ]
    }
  },
  {
    id:'rainbow',
    group:'creative',
    name:'Arcoiris',
    description:'Haz multicolor diagonal sobre luz neutra.',
    scene:{
      background:'#5A5152',
      fog:'#5A5152',
      floor:'#514849',
      exposure:1.04,
      weather:'clear',
      effect:{
        type:'rainbow',
        colorA:'#FF4D5A',
        colorB:'#6B5BFF',
        opacity:44,
        angle:28,
        scale:145
      }
    },
    lighting:{
      ambient:{color:'#A69A98',intensity:24},
      shadow:{color:'#4A3B44',intensity:34},
      bounce:{color:'#F0A26A',intensity:18},
      rim:{color:'#9FE6FF',intensity:20},
      key:{color:'#FFF0D3',intensity:72,azimuth:-28,elevation:48,distance:5.2,softness:66},
      fill:{color:'#B7D5FF',intensity:28,azimuth:58,elevation:24,distance:6.0,softness:76}
    }
  },
  {
    id:'underwater',
    group:'creative',
    name:'Bajo el mar',
    description:'Cian y azul con reflejos acuaticos.',
    scene:{
      background:'#07364D',
      fog:'#0A4E68',
      floor:'#0A3748',
      exposure:.88,
      weather:'underwater',
      effect:{
        type:'underwater',
        colorA:'#55F1FF',
        colorB:'#176BFF',
        opacity:46,
        angle:-16,
        scale:120
      }
    },
    lighting:{
      ambient:{color:'#0E7892',intensity:32},
      shadow:{color:'#062738',intensity:62},
      bounce:{color:'#16A8B7',intensity:22},
      rim:{color:'#66F4FF',intensity:38},
      key:{color:'#57EFFF',intensity:82,azimuth:-26,elevation:66,distance:5.2,softness:44},
      fill:{color:'#1A69FF',intensity:62,azimuth:64,elevation:24,distance:5.8,softness:56},
      extra:[
        {id:'water-top',name:'Reflejo superficie',color:'#B9FFFF',intensity:44,azimuth:8,elevation:82,distance:5.5,softness:26}
      ]
    }
  }
,
  {
    id:'neon-dual',
    group:'creative',
    name:'Neon rojo/cian',
    description:'Rojo y cian enfrentados, intenso y moderno.',
    scene:{
      background:'#171824',
      fog:'#171824',
      floor:'#1C1B28',
      exposure:1.02,
      weather:'clear',
      effect:{
        type:'neon',
        colorA:'#FF4D6D',
        colorB:'#50E6FF',
        opacity:62,
        angle:2,
        scale:126
      }
    },
    lighting:{
      ambient:{color:'#2A3049',intensity:20},
      shadow:{color:'#0E1020',intensity:62},
      bounce:{color:'#324463',intensity:14},
      rim:{color:'#B8F7FF',intensity:22},
      key:{color:'#FF5574',intensity:98,azimuth:-58,elevation:28,distance:5.0,softness:34},
      fill:{color:'#4EE8FF',intensity:84,azimuth:62,elevation:18,distance:5.8,softness:48}
    }
  },
  {
    id:'cyan-floor',
    group:'creative',
    name:'Cian desde abajo',
    description:'Brillo aqua ascendente con sombra magenta.',
    scene:{
      background:'#192437',
      fog:'#192437',
      floor:'#172233',
      exposure:.98,
      weather:'clear',
      effect:{
        type:'glow',
        colorA:'#52F3FF',
        colorB:'#4578FF',
        opacity:34,
        angle:88,
        scale:126
      }
    },
    lighting:{
      ambient:{color:'#315178',intensity:20},
      shadow:{color:'#1E1438',intensity:54},
      bounce:{color:'#48D8EA',intensity:22},
      rim:{color:'#93F7FF',intensity:24},
      key:{color:'#52F3FF',intensity:82,azimuth:174,elevation:-12,distance:4.9,softness:40},
      fill:{color:'#A65BFF',intensity:32,azimuth:-34,elevation:34,distance:5.8,softness:68}
    }
  },
  {
    id:'purple-gold-split',
    group:'creative',
    name:'Morado + amarillo',
    description:'Base violeta con haz amarillo intenso.',
    scene:{
      background:'#231836',
      fog:'#231836',
      floor:'#241B31',
      exposure:.96,
      weather:'clear',
      effect:{
        type:'stripe',
        colorA:'#FFE56A',
        colorB:'#7A4BFF',
        opacity:70,
        angle:-8,
        scale:92
      }
    },
    lighting:{
      ambient:{color:'#4F3A77',intensity:24},
      shadow:{color:'#170F25',intensity:64},
      bounce:{color:'#6C46A8',intensity:14},
      rim:{color:'#DFA2FF',intensity:22},
      key:{color:'#FFE768',intensity:108,azimuth:-12,elevation:54,distance:5.0,softness:18},
      fill:{color:'#8A52FF',intensity:46,azimuth:72,elevation:20,distance:5.8,softness:68}
    }
  },
  {
    id:'window-cool',
    group:'creative',
    name:'Ventana fria',
    description:'Ventana azulada con sombra profunda.',
    scene:{
      background:'#203247',
      fog:'#203247',
      floor:'#1C2837',
      exposure:.96,
      weather:'clear',
      effect:{
        type:'window',
        colorA:'#D7EEFF',
        colorB:'#6FC9FF',
        opacity:54,
        angle:-14,
        scale:112
      }
    },
    lighting:{
      ambient:{color:'#365B7A',intensity:18},
      shadow:{color:'#0F1B2A',intensity:60},
      bounce:{color:'#4D7E9C',intensity:12},
      rim:{color:'#DCF4FF',intensity:28},
      key:{color:'#E4F6FF',intensity:88,azimuth:-38,elevation:42,distance:5.1,softness:22},
      fill:{color:'#74CFFF',intensity:30,azimuth:48,elevation:16,distance:6.0,softness:76}
    }
  },
  {
    id:'blinds-golden',
    group:'creative',
    name:'Persianas calidas',
    description:'Bandas de sol dorado como persianas.',
    scene:{
      background:'#47352D',
      fog:'#47352D',
      floor:'#413029',
      exposure:1.03,
      weather:'clear',
      effect:{
        type:'blinds',
        colorA:'#FFD577',
        colorB:'#FFB453',
        opacity:62,
        angle:-18,
        scale:100
      }
    },
    lighting:{
      ambient:{color:'#795C4F',intensity:20},
      shadow:{color:'#281E1D',intensity:54},
      bounce:{color:'#D08A57',intensity:20},
      rim:{color:'#FFD998',intensity:12},
      key:{color:'#FFD578',intensity:96,azimuth:-48,elevation:24,distance:5.1,softness:18},
      fill:{color:'#8D6754',intensity:18,azimuth:58,elevation:16,distance:6.1,softness:72}
    }
  },
  {
    id:'bokeh-gold',
    group:'creative',
    name:'Circulos dorados',
    description:'Discos de luz suaves tipo bokeh.',
    scene:{
      background:'#4A3A31',
      fog:'#4A3A31',
      floor:'#40342E',
      exposure:1.00,
      weather:'clear',
      effect:{
        type:'bokeh',
        colorA:'#FFF1A4',
        colorB:'#FFB55D',
        opacity:58,
        angle:0,
        scale:128
      }
    },
    lighting:{
      ambient:{color:'#7E675A',intensity:22},
      shadow:{color:'#2A2322',intensity:46},
      bounce:{color:'#DA8F5A',intensity:18},
      rim:{color:'#FFE4A1',intensity:14},
      key:{color:'#FFE5A2',intensity:82,azimuth:-24,elevation:36,distance:5.2,softness:56},
      fill:{color:'#FFBB68',intensity:34,azimuth:68,elevation:18,distance:6.0,softness:80}
    }
  },
  {
    id:'sparkle-dream',
    group:'creative',
    name:'Brillos lilas',
    description:'Puntos de brillo rosas y lilas.',
    scene:{
      background:'#3F304B',
      fog:'#3F304B',
      floor:'#37293F',
      exposure:1.00,
      weather:'clear',
      effect:{
        type:'sparkles',
        colorA:'#FFE1FF',
        colorB:'#C28BFF',
        opacity:56,
        angle:0,
        scale:114
      }
    },
    lighting:{
      ambient:{color:'#6E5685',intensity:22},
      shadow:{color:'#281B34',intensity:48},
      bounce:{color:'#C57DE1',intensity:18},
      rim:{color:'#F6D3FF',intensity:22},
      key:{color:'#FFD9FF',intensity:78,azimuth:-20,elevation:44,distance:5.2,softness:64},
      fill:{color:'#BE8BFF',intensity:40,azimuth:54,elevation:22,distance:5.9,softness:78}
    }
  },
  {
    id:'flash-editorial',
    group:'creative',
    name:'Flash duro',
    description:'Flash frontal brillante con sombra seca.',
    scene:{
      background:'#343943',
      fog:'#343943',
      floor:'#2B3038',
      exposure:1.10,
      weather:'clear',
      effect:{
        type:'flash',
        colorA:'#FFFFFF',
        colorB:'#BFD7FF',
        opacity:78,
        angle:0,
        scale:96
      }
    },
    lighting:{
      ambient:{color:'#69727F',intensity:12},
      shadow:{color:'#1C2026',intensity:66},
      bounce:{color:'#7C8796',intensity:8},
      rim:{color:'#E8F3FF',intensity:16},
      key:{color:'#FFFFFF',intensity:122,azimuth:0,elevation:24,distance:4.8,softness:10},
      fill:{color:'#BFD7FF',intensity:22,azimuth:18,elevation:8,distance:5.9,softness:34}
    }
  },
  {
    id:'caustics-sea',
    group:'creative',
    name:'Causticas marinas',
    description:'Ondas de agua proyectadas sobre el sujeto.',
    scene:{
      background:'#103550',
      fog:'#103550',
      floor:'#133044',
      exposure:.94,
      weather:'clear',
      effect:{
        type:'caustics',
        colorA:'#7DE7FF',
        colorB:'#2EA9E6',
        opacity:64,
        angle:8,
        scale:120
      }
    },
    lighting:{
      ambient:{color:'#245E81',intensity:22},
      shadow:{color:'#0B1E31',intensity:56},
      bounce:{color:'#2E86B2',intensity:18},
      rim:{color:'#ACF4FF',intensity:24},
      key:{color:'#85EBFF',intensity:84,azimuth:-34,elevation:52,distance:5.1,softness:32},
      fill:{color:'#30ABE8',intensity:44,azimuth:62,elevation:20,distance:6.0,softness:62}
    }
  },
  {
    id:'underwater-teal',
    group:'creative',
    name:'Bajo el mar',
    description:'Azul verdoso con bandas de agua.',
    scene:{
      background:'#0B3750',
      fog:'#0B3750',
      floor:'#102B39',
      exposure:.92,
      weather:'clear',
      effect:{
        type:'underwater',
        colorA:'#7DEBFF',
        colorB:'#0E8CD8',
        opacity:54,
        angle:10,
        scale:118
      }
    },
    lighting:{
      ambient:{color:'#2B6585',intensity:24},
      shadow:{color:'#0B1C2B',intensity:52},
      bounce:{color:'#1B8EAA',intensity:18},
      rim:{color:'#A4F1FF',intensity:26},
      key:{color:'#8AEFFF',intensity:74,azimuth:-30,elevation:48,distance:5.2,softness:40},
      fill:{color:'#1494DE',intensity:42,azimuth:60,elevation:18,distance:6.0,softness:70}
    }
  },
  {
    id:'rainbow-prism',
    group:'creative',
    name:'Arcoiris prisma',
    description:'Haz multicolor tipo prisma.',
    scene:{
      background:'#2D253B',
      fog:'#2D253B',
      floor:'#241E30',
      exposure:1.00,
      weather:'clear',
      effect:{
        type:'rainbow',
        colorA:'#FFFFFF',
        colorB:'#FFFFFF',
        opacity:72,
        angle:-12,
        scale:118
      }
    },
    lighting:{
      ambient:{color:'#5B4C72',intensity:20},
      shadow:{color:'#1A1526',intensity:54},
      bounce:{color:'#7F69A3',intensity:12},
      rim:{color:'#F0E8FF',intensity:18},
      key:{color:'#FFFFFF',intensity:88,azimuth:-22,elevation:40,distance:5.0,softness:26},
      fill:{color:'#A8C4FF',intensity:24,azimuth:52,elevation:14,distance:6.0,softness:68}
    }
  },
  {
    id:'leaf-dense',
    group:'creative',
    name:'Hojas densas',
    description:'Sombras y destellos de follaje mas cerrado.',
    scene:{
      background:'#314232',
      fog:'#314232',
      floor:'#293629',
      exposure:.96,
      weather:'clear',
      effect:{
        type:'leaves',
        colorA:'#F3E26A',
        colorB:'#4E8C45',
        opacity:48,
        angle:18,
        scale:90
      }
    },
    lighting:{
      ambient:{color:'#617A57',intensity:22},
      shadow:{color:'#1E2A1F',intensity:58},
      bounce:{color:'#719851',intensity:18},
      rim:{color:'#D8E475',intensity:12},
      key:{color:'#EEDF6D',intensity:88,azimuth:32,elevation:64,distance:5.1,softness:20},
      fill:{color:'#5E994D',intensity:34,azimuth:-60,elevation:26,distance:6.0,softness:64}
    }
  },
  {
    id:'sun-blast',
    group:'creative',
    name:'Sol brillante',
    description:'Sol fuerte amarillo con borde naranja.',
    scene:{
      background:'#4D3A2B',
      fog:'#4D3A2B',
      floor:'#3E3128',
      exposure:1.12,
      weather:'clear',
      effect:{
        type:'glow',
        colorA:'#FFE869',
        colorB:'#FF9E3D',
        opacity:42,
        angle:-34,
        scale:144
      }
    },
    lighting:{
      ambient:{color:'#6D5548',intensity:18},
      shadow:{color:'#221826',intensity:60},
      bounce:{color:'#D57F40',intensity:20},
      rim:{color:'#FFD96C',intensity:26},
      key:{color:'#FFE86C',intensity:124,azimuth:-78,elevation:34,distance:5.0,softness:24},
      fill:{color:'#8454A8',intensity:18,azimuth:54,elevation:18,distance:6.0,softness:74},
      extra:[
        {id:'sun-orange-edge',name:'Borde solar',color:'#FF8A32',intensity:54,azimuth:158,elevation:32,distance:5.8,softness:40}
      ]
    }
  },
  {
    id:'blue-red-drama',
    group:'creative',
    name:'Azul y rojo dramatico',
    description:'Contraste cinematografico entre azul y rojo.',
    scene:{
      background:'#171B28',
      fog:'#171B28',
      floor:'#1B1D27',
      exposure:.96,
      weather:'clear',
      effect:{
        type:'split',
        colorA:'#3EAEFF',
        colorB:'#FF4A52',
        opacity:56,
        angle:0,
        scale:132
      }
    },
    lighting:{
      ambient:{color:'#2B3551',intensity:18},
      shadow:{color:'#0D1018',intensity:64},
      bounce:{color:'#263E66',intensity:10},
      rim:{color:'#C8D8FF',intensity:12},
      key:{color:'#3FAFFF',intensity:86,azimuth:-68,elevation:24,distance:5.2,softness:34},
      fill:{color:'#FF5059',intensity:78,azimuth:66,elevation:20,distance:5.8,softness:42}
    }
  }

];

export function atmosphere3dById(id){
  return THREE_ATMOSPHERES.find(
    item=>item.id===id
  )||THREE_ATMOSPHERES[0];
}

function makeLight(
  id,
  name,
  config
){
  return{
    id,
    name,
    color:config.color,
    intensity:config.intensity,
    azimuth:config.azimuth,
    elevation:config.elevation,
    distance:config.distance,
    softness:config.softness,
    enabled:true
  };
}

export function build3dAtmosphere(
  id,
  currentLighting={}
){
  const preset=
    atmosphere3dById(id);

  const config=
    preset.lighting;

  const extra=
    Array.isArray(config.extra)
      ?config.extra
      :[];

  return{
    preset,
    scene:{
      id:preset.id,
      ...preset.scene
    },
    lighting:{
      enabled:true,
      showHelpers:
        currentLighting.showHelpers??true,
      selectedLightId:'key',
      projector:{
        ...projectorFromEffect(
          preset.scene?.effect||{}
        ),
        lightId:'key'
      },
      ambient:{...config.ambient},
      shadow:{...config.shadow},
      bounce:{...config.bounce},
      rim:{...config.rim},
      lights:[
        makeLight(
          'key',
          'Luz principal',
          config.key
        ),
        makeLight(
          'fill',
          'Relleno',
          config.fill
        ),
        ...extra.map(
          (light,index)=>
            makeLight(
              light.id||
              `creative-${index+1}`,
              light.name||
              `Luz ${index+3}`,
              light
            )
        )
      ].slice(0,8)
    }
  };
}
