(function(){'use strict';
  const clamp=(v,min=0,max=255)=>Math.max(min,Math.min(max,v));
  function canvas(w,h){const c=document.createElement('canvas');c.width=Math.max(1,Math.round(w));c.height=Math.max(1,Math.round(h));return c}
  function copy(source){const c=canvas(source.width,source.height);c.getContext('2d').drawImage(source,0,0);return c}
  function parseHex(hex){const value=String(hex||'#000000').replace('#','');const full=value.length===3?value.split('').map(v=>v+v).join(''):value.padEnd(6,'0').slice(0,6);return[parseInt(full.slice(0,2),16)||0,parseInt(full.slice(2,4),16)||0,parseInt(full.slice(4,6),16)||0]}
  function hueRotate(r,g,b,deg){if(!deg)return[r,g,b];const a=deg*Math.PI/180,cos=Math.cos(a),sin=Math.sin(a);return[
    (.213+cos*.787-sin*.213)*r+(.715-cos*.715-sin*.715)*g+(.072-cos*.072+sin*.928)*b,
    (.213-cos*.213+sin*.143)*r+(.715+cos*.285+sin*.140)*g+(.072-cos*.072-sin*.283)*b,
    (.213-cos*.213-sin*.787)*r+(.715-cos*.715+sin*.715)*g+(.072+cos*.928+sin*.072)*b]}
  function colorAdjust(source,state){const a=state.adjustments,f=state.filters;const neutral=a.brightness===0&&a.contrast===0&&a.saturation===0&&a.exposure===0&&a.temperature===0&&a.hue===0&&a.vibrance===0&&a.gamma===1&&a.shadows===0&&a.highlights===0&&a.whites===0&&a.blacks===0&&f.grayscale===0&&f.monochrome===0&&f.sepia===0&&f.invert===0;if(neutral)return source;
    const out=copy(source),ctx=out.getContext('2d',{willReadFrequently:true}),img=ctx.getImageData(0,0,out.width,out.height),d=img.data;const exposure=Math.pow(2,a.exposure/100*2),bright=a.brightness*2.55,cv=a.contrast*2.55,contrast=(259*(cv+255))/(255*(259-cv)),satBase=1+a.saturation/100,vib=a.vibrance/100,grayMix=f.grayscale/100,monoMix=f.monochrome/100,sepiaMix=f.sepia/100,invertMix=f.invert/100,mono=parseHex(f.monochromeColor),gamma=Math.max(.1,a.gamma);
    for(let i=0;i<d.length;i+=4){let r=d[i]*exposure+bright,g=d[i+1]*exposure+bright,b=d[i+2]*exposure+bright;r=contrast*(r-128)+128;g=contrast*(g-128)+128;b=contrast*(b-128)+128;r+=a.temperature*.7;b-=a.temperature*.7;[r,g,b]=hueRotate(r,g,b,a.hue);let l=.299*r+.587*g+.114*b,max=Math.max(r,g,b),min=Math.min(r,g,b),sat=satBase*(1+vib*(1-(max-min)/255));r=l+(r-l)*sat;g=l+(g-l)*sat;b=l+(b-l)*sat;l=clamp(.299*r+.587*g+.114*b);const low=Math.pow(1-l/255,2),high=Math.pow(l/255,2),shift=a.shadows*1.2*low+a.highlights*1.2*high+a.whites*Math.pow(l/255,5)+a.blacks*Math.pow(1-l/255,5);r+=shift;g+=shift;b+=shift;r=255*Math.pow(clamp(r)/255,1/gamma);g=255*Math.pow(clamp(g)/255,1/gamma);b=255*Math.pow(clamp(b)/255,1/gamma);l=.299*r+.587*g+.114*b;r+=(l-r)*grayMix;g+=(l-g)*grayMix;b+=(l-b)*grayMix;if(monoMix){const mr=mono[0]*l/255,mg=mono[1]*l/255,mb=mono[2]*l/255;r+=(mr-r)*monoMix;g+=(mg-g)*monoMix;b+=(mb-b)*monoMix}if(sepiaMix){const sr=r*.393+g*.769+b*.189,sg=r*.349+g*.686+b*.168,sb=r*.272+g*.534+b*.131;r+=(sr-r)*sepiaMix;g+=(sg-g)*sepiaMix;b+=(sb-b)*sepiaMix}r+=(255-2*r)*invertMix;g+=(255-2*g)*invertMix;b+=(255-2*b)*invertMix;d[i]=clamp(r);d[i+1]=clamp(g);d[i+2]=clamp(b)}ctx.putImageData(img,0,0);return out}
  function cssBlur(source,radius){if(radius<=.05)return source;const out=canvas(source.width,source.height),ctx=out.getContext('2d');ctx.filter=`blur(${Math.min(80,radius)}px)`;ctx.drawImage(source,0,0);ctx.filter='none';return out}
  function pixelate(source,size){if(size<=1)return source;const w=Math.max(1,Math.round(source.width/size)),h=Math.max(1,Math.round(source.height/size)),small=canvas(w,h),sctx=small.getContext('2d');sctx.imageSmoothingEnabled=false;sctx.drawImage(source,0,0,w,h);const out=canvas(source.width,source.height),ctx=out.getContext('2d');ctx.imageSmoothingEnabled=false;ctx.drawImage(small,0,0,out.width,out.height);return out}
  function motionBlur(source,distance,angle){if(distance<=.1)return source;const out=canvas(source.width,source.height),ctx=out.getContext('2d'),samples=Math.max(3,Math.min(26,Math.ceil(distance/2)+3)),rad=angle*Math.PI/180;ctx.globalAlpha=1/samples;for(let i=0;i<samples;i++){const off=(i/(samples-1)-.5)*distance;ctx.drawImage(source,Math.cos(rad)*off,Math.sin(rad)*off)}ctx.globalAlpha=1;return out}
  function sharpen(source,spec,scale){if(spec.amount<=0)return source;const blurred=cssBlur(source,Math.max(.25,spec.radius*scale)),out=copy(source),ctx=out.getContext('2d',{willReadFrequently:true}),orig=ctx.getImageData(0,0,out.width,out.height),bd=blurred.getContext('2d',{willReadFrequently:true}).getImageData(0,0,out.width,out.height).data,amount=spec.amount/100*2.1,threshold=spec.threshold;for(let i=0;i<orig.data.length;i+=4)for(let c=0;c<3;c++){const detail=orig.data[i+c]-bd[i+c];if(Math.abs(detail)>=threshold)orig.data[i+c]=clamp(orig.data[i+c]+detail*amount)}ctx.putImageData(orig,0,0);return out}
  function vignetteAndGrain(source,state,quality){const out=copy(source),ctx=out.getContext('2d'),f=state.filters,g=state.grain,v=f.vignette/100;if(v>0){const cx=out.width/2,cy=out.height/2,start=Math.max(.03,f.vignetteSize/100)*Math.min(out.width,out.height)*.7,outer=Math.max(start+1,start+Math.max(out.width,out.height)*Math.max(.04,f.vignetteSoftness/100)),grad=ctx.createRadialGradient(cx,cy,start,cx,cy,outer);grad.addColorStop(0,'rgba(0,0,0,0)');grad.addColorStop(1,`rgba(0,0,0,${v})`);ctx.fillStyle=grad;ctx.fillRect(0,0,out.width,out.height)}const strength=g.amount/100*g.opacity;if(strength>0){const factor=quality==='fast'?1.6:1,cell=Math.max(1,g.size*factor,Math.sqrt(out.width*out.height/350000)),nw=Math.max(1,Math.ceil(out.width/cell)),nh=Math.max(1,Math.ceil(out.height/cell)),noise=canvas(nw,nh),nctx=noise.getContext('2d'),image=nctx.createImageData(nw,nh),d=image.data;let seed=0x6d2b79f5;for(let i=0;i<d.length;i+=4){seed=(seed*1664525+1013904223)>>>0;const val=seed>>>24;d[i]=d[i+1]=d[i+2]=val;d[i+3]=255}nctx.putImageData(image,0,0);ctx.save();ctx.imageSmoothingEnabled=false;ctx.globalCompositeOperation='soft-light';ctx.globalAlpha=Math.min(.75,strength*.9);ctx.drawImage(noise,0,0,out.width,out.height);ctx.restore()}return out}
  window.ImageFilters={canvas,copy,colorAdjust,cssBlur,pixelate,motionBlur,sharpen,vignetteAndGrain,parseHex};
}());
