(function(){'use strict';
  const $=s=>document.querySelector(s),clone=ImageState.clone;
  let state=ImageState.defaults(),source=null,sourceBlob=null,sourceName='',sourceWidth=0,sourceHeight=0,currentProjectId=null,zoom=1,focusMode=false,drag=null,recoveryTimer=0,toastTimer=0;
  const history=new ImageHistory.History(90);
  const preview=new ImagePreviewPipeline.PreviewPipeline($('#previewCanvas'),busy=>{$('#renderBadge').hidden=!busy},text=>{$('#statusText').textContent=text});

  function toast(text){clearTimeout(toastTimer);const el=$('#toast');el.textContent=text;el.classList.add('show');toastTimer=setTimeout(()=>el.classList.remove('show'),2300)}
  function setEnabled(enabled){$('#editorControls').classList.toggle('disabled',!enabled);['#saveProjectBtn','#saveTemplateBtn','#exportTopBtn'].forEach(s=>$(s).disabled=!enabled)}
  function dimensionsLabel(){return source?`${sourceWidth.toLocaleString('es-ES')} × ${sourceHeight.toLocaleString('es-ES')} px`:''}
  function setSourceMeta(){if(!source)return;$('#fileName').textContent=sourceName||'Imagen';$('#imageMeta').textContent=dimensionsLabel();$('#emptyState').hidden=true;$('#canvasWrap').hidden=false;setEnabled(true)}
  function getExportConfig(){return{format:$('#exportFormat').value,scale:Number($('#exportScale').value)||1,width:Number($('#exportWidth').value)||1,height:Number($('#exportHeight').value)||1,quality:Number($('#exportQuality').value)||92,transparent:$('#transparentBg').checked,background:$('#backgroundColor').value}}
  function projectPayload(){return{schema:'kaoru-image-studio-project',version:13,state:clone(state),zoom,focusMode:false,export:getExportConfig(),fileName:sourceName}}
  function scheduleRecovery(){if(!sourceBlob)return;clearTimeout(recoveryTimer);recoveryTimer=setTimeout(()=>ImageStorage.save({payload:projectPayload(),source:sourceBlob,fileName:sourceName}).catch(console.warn),180)}

  function updateFocusRing(){const ring=$('#focusRing'),canvas=$('#previewCanvas');if(!source||!focusMode||!state.lens.enabled){ring.hidden=true;return}ring.hidden=false;const w=canvas.offsetWidth,h=canvas.offsetHeight,r=state.lens.focusRadius*Math.min(w,h);ring.style.width=`${r*2}px`;ring.style.height=`${r*2}px`;ring.style.left=`${state.lens.focusX*w-r}px`;ring.style.top=`${state.lens.focusY*h-r}px`}
  function applyZoom(){const c=$('#previewCanvas');if(!source)return;c.style.width=`${Math.max(1,Math.round(c.width*zoom))}px`;c.style.height=`${Math.max(1,Math.round(c.height*zoom))}px`;$('#zoomValue').textContent=`${Math.round(zoom*100)}%`;requestAnimationFrame(updateFocusRing)}
  function fitView(){if(!source)return;const vp=$('#canvasViewport'),c=$('#previewCanvas'),availableW=Math.max(80,vp.clientWidth-70),availableH=Math.max(80,vp.clientHeight-70);zoom=Math.max(.08,Math.min(1,availableW/c.width,availableH/c.height));applyZoom()}

  function previewFast(){preview.setState(state);preview.schedule('fast');updateFocusRing()}
  function previewFull(){preview.setState(state);preview.schedule('full');scheduleRecovery();updateFocusRing()}
  function commit(label){history.push(state);previewFull();scheduleRecovery();$('#statusText').textContent=label||'Cambio guardado'}
  function applyHistory(next){if(!next)return;state=ImageState.merge(next);syncAll();preview.setState(state);preview.schedule('full',0);scheduleRecovery()}
  history.onChange=({canUndo,canRedo})=>{$('#undoBtn').disabled=!canUndo;$('#redoBtn').disabled=!canRedo};

  function buildDynamicControls(){[['#adjustmentControls','adjustments'],['#filterControls','filters'],['#grainControls','grain'],['#lensControls','lens']].forEach(([selector,group])=>{const el=$(selector);el.dataset.group=group;ImageUI.build(el,state,()=>previewFast(),path=>commit(`Ajuste: ${path}`))})}
  function syncAll(){ImageUI.sync(state);$('#monochromeColor').value=state.filters.monochromeColor;$('#lensEnabled').checked=state.lens.enabled;$('#lensShape').value=state.lens.shape;$('#transformX').value=Math.round(state.transform.x);$('#transformY').value=Math.round(state.transform.y);$('#scaleX').value=Math.round(state.transform.scaleX*100);$('#scaleY').value=Math.round(state.transform.scaleY*100);$('#rotation').value=state.transform.rotation;$('#imageOpacity').value=Math.round(state.adjustments.opacity*100);$('#aspectLock').checked=state.transform.aspectLock;$('#cropX').value=Math.round(state.crop.x);$('#cropY').value=Math.round(state.crop.y);$('#cropWidth').value=Math.round(state.crop.width);$('#cropHeight').value=Math.round(state.crop.height);$('#focusModeBtn').classList.toggle('active',focusMode);updateFocusRing();updateExportInfo()}

  async function blobToSource(blob,name){if(source&&typeof source.close==='function')try{source.close()}catch(_){};let drawable;try{drawable=await createImageBitmap(blob,{imageOrientation:'from-image'})}catch(_){drawable=await new Promise((resolve,reject)=>{const url=URL.createObjectURL(blob),img=new Image();img.onload=()=>{URL.revokeObjectURL(url);resolve(img)};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('No se pudo decodificar la imagen.'))};img.src=url})}source=drawable;sourceBlob=blob;sourceName=name||blob.name||'imagen';sourceWidth=drawable.width||drawable.naturalWidth;sourceHeight=drawable.height||drawable.naturalHeight}
  function clampCrop(){state.crop.x=Math.max(0,Math.min(sourceWidth-1,Number(state.crop.x)||0));state.crop.y=Math.max(0,Math.min(sourceHeight-1,Number(state.crop.y)||0));state.crop.width=Math.max(1,Math.min(sourceWidth-state.crop.x,Number(state.crop.width)||sourceWidth));state.crop.height=Math.max(1,Math.min(sourceHeight-state.crop.y,Number(state.crop.height)||sourceHeight))}
  async function openBlob(blob,name,payload=null,projectId=null,asTemplate=false){await blobToSource(blob,name);state=payload?ImageState.normalizeProject(payload):ImageState.defaults();if(!payload){state.crop={x:0,y:0,width:sourceWidth,height:sourceHeight}}clampCrop();currentProjectId=asTemplate?null:projectId;zoom=Math.max(.08,Math.min(4,Number(payload&&payload.zoom)||1));focusMode=false;setSourceMeta();syncAll();history.reset(state);preview.setSource(source,state);preview.schedule('full',0);restoreExport(payload&&payload.export);setTimeout(()=>payload&&payload.zoom?applyZoom():fitView(),80);scheduleRecovery()}
  async function loadFile(file){if(!file||!/^image\/(png|jpeg|webp)$/i.test(file.type)){toast('Selecciona PNG, JPG/JPEG o WEBP.');return}try{await openBlob(file,file.name);currentProjectId=null;toast('Imagen importada. Image Studio V2 listo.')}catch(error){console.error(error);toast(error.message||'No se pudo abrir la imagen.')}}

  function restoreExport(exp){if(!source)return;const e=exp||{};$('#exportFormat').value=e.format||'png';$('#exportScale').value=String(e.scale||1);$('#exportQuality').value=e.quality||92;$('#exportQuality').parentElement.querySelector('output').textContent=`${e.quality||92}%`;$('#transparentBg').checked=e.transparent!==false;$('#backgroundColor').value=e.background||'#ffffff';if(e.width&&e.height){$('#exportWidth').value=e.width;$('#exportHeight').value=e.height}else updateExportDimensions(true);syncExportVisibility();updateExportInfo()}
  function updateExportDimensions(fromScale=true){if(!source)return;if(fromScale){const scale=Number($('#exportScale').value)||1;$('#exportWidth').value=Math.max(1,Math.round(state.crop.width*scale));$('#exportHeight').value=Math.max(1,Math.round(state.crop.height*scale))}updateExportInfo()}
  function updateExportInfo(){if(!source){$('#exportInfo').textContent='';return}const w=Number($('#exportWidth').value)||0,h=Number($('#exportHeight').value)||0;$('#exportInfo').textContent=`${w.toLocaleString('es-ES')} × ${h.toLocaleString('es-ES')} px · render desde la fuente original`}
  function syncExportVisibility(){const format=$('#exportFormat').value;$('#qualityRow').classList.toggle('visible',format!=='png');if(format==='jpeg')$('#transparentBg').checked=false;$('#backgroundRow').classList.toggle('visible',!$('#transparentBg').checked||format==='jpeg')}

  async function exportImage(){if(!source)return;const cfg=getExportConfig(),pixels=cfg.width*cfg.height;if(cfg.width<1||cfg.height<1||pixels>50000000){toast('La exportación admite hasta 50 megapíxeles.');return}const buttons=[$('#exportBtn'),$('#exportTopBtn')];buttons.forEach(b=>b.disabled=true);try{const background=cfg.transparent&&cfg.format!=='jpeg'?null:cfg.background,canvas=await ImageExportPipeline.render(source,state,{width:cfg.width,height:cfg.height,background},t=>$('#statusText').textContent=t),blob=await ImageExportPipeline.blob(canvas,cfg.format,cfg.quality/100),url=URL.createObjectURL(blob),a=document.createElement('a'),ext=cfg.format==='jpeg'?'jpg':cfg.format;a.href=url;a.download=window.StudioNaming?StudioNaming.file('IMG',ext):`IMG-${Date.now().toString(36).toUpperCase()}.${ext}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);$('#statusText').textContent=`Exportada · ${cfg.width} × ${cfg.height}px`;toast('Imagen exportada correctamente.')}catch(error){console.error(error);toast('No se pudo exportar la imagen.');$('#statusText').textContent='Error de exportación'}finally{buttons.forEach(b=>b.disabled=false)}}

  function thumbnail(){try{return $('#previewCanvas').toDataURL('image/jpeg',.72)}catch(_){return null}}
  async function saveGallery(kind){if(!sourceBlob||!window.StudioGallery)return;const base=(sourceName||'Imagen').replace(/\.[^.]+$/,''),suggested=kind==='template'?`${base} · plantilla`:base,name=(prompt(kind==='template'?'Nombre de la plantilla:':'Nombre del diseño:',suggested)||'').trim();if(!name)return;try{const record=await StudioGallery.save({id:kind==='project'?currentProjectId:null,studio:'image',kind,name,payload:projectPayload(),assets:{source:sourceBlob,fileName:sourceName},thumbnail:thumbnail()});if(kind==='project')currentProjectId=record.id;toast(kind==='template'?'Plantilla guardada.':'Diseño guardado.')}catch(error){console.error(error);toast('No se pudo guardar en la Galería.')}}
  async function galleryLaunch(){if(!window.StudioGallery)return false;try{const record=await StudioGallery.consumeLaunchIntent('image');if(!record)return false;const blob=record.assets&&record.assets.source;if(!(blob instanceof Blob))throw new Error('El proyecto no contiene su imagen fuente.');await openBlob(blob,record.assets.fileName||record.name,record.payload,record.id,record.kind==='template');toast(record.kind==='template'?'Plantilla abierta como diseño nuevo.':'Proyecto abierto desde Galería.');return true}catch(error){console.error(error);toast(error.message||'No se pudo abrir el proyecto.');return false}}

  async function recoveryPrompt(){try{const saved=await ImageStorage.load();if(!saved||!(saved.source instanceof Blob)||!saved.payload)return;const date=new Date(saved.savedAt||Date.now());$('#recoveryMeta').textContent=`${saved.fileName||saved.payload.fileName||'Imagen'} · ${date.toLocaleString('es-PE')}`;$('#recoveryModal').hidden=false;$('#recoverBtn').onclick=async()=>{try{await openBlob(saved.source,saved.fileName||'Imagen recuperada',saved.payload);$('#recoveryModal').hidden=true;toast('Progreso recuperado.')}catch(error){console.error(error);toast('No se pudo recuperar la sesión.')}};$('#newBtn').onclick=async()=>{await ImageStorage.clear();$('#recoveryModal').hidden=true;toast('Proyecto nuevo listo.')}}catch(error){console.warn(error)}}

  function bind(){const input=$('#fileInput'),drop=$('#dropZone'),viewport=$('#canvasViewport');input.addEventListener('change',e=>loadFile(e.target.files[0]));['dragenter','dragover'].forEach(t=>drop.addEventListener(t,e=>{e.preventDefault();drop.classList.add('dragover')}));['dragleave','drop'].forEach(t=>drop.addEventListener(t,e=>{e.preventDefault();drop.classList.remove('dragover')}));drop.addEventListener('drop',e=>loadFile(e.dataTransfer.files[0]));viewport.addEventListener('dragover',e=>e.preventDefault());viewport.addEventListener('drop',e=>{e.preventDefault();loadFile(e.dataTransfer.files[0])});
    $('#monochromeColor').addEventListener('input',e=>{state.filters.monochromeColor=e.target.value;previewFast()});$('#monochromeColor').addEventListener('change',()=>commit('Color monocromático'));
    $('#lensEnabled').addEventListener('change',e=>{state.lens.enabled=e.target.checked;if(!state.lens.enabled)focusMode=false;syncAll();commit('Lens Blur')});$('#lensShape').addEventListener('change',e=>{state.lens.shape=e.target.value;commit('Forma de apertura')});$('#focusModeBtn').addEventListener('click',()=>{focusMode=!focusMode;if(focusMode&&!state.lens.enabled){state.lens.enabled=true;$('#lensEnabled').checked=true;history.push(state)}syncAll();toast(focusMode?'Haz clic donde debe quedar el foco.':'Modo de foco desactivado.')});
    const transformIds=['transformX','transformY','scaleX','scaleY','rotation','imageOpacity'];transformIds.forEach(id=>{$(`#${id}`).addEventListener('input',()=>{const lock=state.transform.aspectLock,active=id;state.transform.x=Number($('#transformX').value)||0;state.transform.y=Number($('#transformY').value)||0;if(active==='scaleX'){state.transform.scaleX=Math.max(.01,(Number($('#scaleX').value)||100)/100);if(lock){state.transform.scaleY=state.transform.scaleX;$('#scaleY').value=$('#scaleX').value}}else if(active==='scaleY'){state.transform.scaleY=Math.max(.01,(Number($('#scaleY').value)||100)/100);if(lock){state.transform.scaleX=state.transform.scaleY;$('#scaleX').value=$('#scaleY').value}}state.transform.rotation=Number($('#rotation').value)||0;state.adjustments.opacity=Math.max(0,Math.min(1,(Number($('#imageOpacity').value)||0)/100));previewFast()});$(`#${id}`).addEventListener('change',()=>commit('Transformación'))});
    $('#aspectLock').addEventListener('change',e=>{state.transform.aspectLock=e.target.checked;commit('Bloqueo de proporción')});$('#flipXBtn').addEventListener('click',()=>{state.transform.flipX=!state.transform.flipX;commit('Voltear horizontal')});$('#flipYBtn').addEventListener('click',()=>{state.transform.flipY=!state.transform.flipY;commit('Voltear vertical')});$('#resetTransformBtn').addEventListener('click',()=>{state.transform=ImageState.defaults().transform;state.adjustments.opacity=1;syncAll();commit('Restablecer transformación')});
    $('#applyCropBtn').addEventListener('click',()=>{if(!source)return;state.crop={x:Number($('#cropX').value)||0,y:Number($('#cropY').value)||0,width:Number($('#cropWidth').value)||1,height:Number($('#cropHeight').value)||1};clampCrop();syncAll();preview.updateDimensions(true);preview.setState(state);preview.schedule('full',0);updateExportDimensions(true);history.push(state);setTimeout(fitView,60);scheduleRecovery()});$('#resetCropBtn').addEventListener('click',()=>{if(!source)return;state.crop={x:0,y:0,width:sourceWidth,height:sourceHeight};syncAll();preview.updateDimensions(true);preview.schedule('full',0);updateExportDimensions(true);history.push(state);setTimeout(fitView,60);scheduleRecovery()});
    const c=$('#previewCanvas');c.addEventListener('pointerdown',e=>{if(!source)return;const rect=c.getBoundingClientRect();if(focusMode){state.lens.focusX=Math.max(0,Math.min(1,(e.clientX-rect.left)/rect.width));state.lens.focusY=Math.max(0,Math.min(1,(e.clientY-rect.top)/rect.height));updateFocusRing();previewFast();history.push(state);previewFull();return}drag={id:e.pointerId,startX:e.clientX,startY:e.clientY,x:state.transform.x,y:state.transform.y,rect};c.setPointerCapture(e.pointerId)});c.addEventListener('pointermove',e=>{if(!drag)return;state.transform.x=drag.x+(e.clientX-drag.startX)*state.crop.width/drag.rect.width;state.transform.y=drag.y+(e.clientY-drag.startY)*state.crop.height/drag.rect.height;$('#transformX').value=Math.round(state.transform.x);$('#transformY').value=Math.round(state.transform.y);previewFast()});const finishDrag=()=>{if(drag){drag=null;commit('Mover imagen')}};c.addEventListener('pointerup',finishDrag);c.addEventListener('pointercancel',finishDrag);
    $('#undoBtn').addEventListener('click',()=>applyHistory(history.undo()));$('#redoBtn').addEventListener('click',()=>applyHistory(history.redo()));document.addEventListener('keydown',e=>{const mod=e.ctrlKey||e.metaKey;if(mod&&e.key.toLowerCase()==='z'){e.preventDefault();applyHistory(e.shiftKey?history.redo():history.undo())}});
    $('#zoomOut').addEventListener('click',()=>{zoom=Math.max(.08,zoom/1.2);applyZoom()});$('#zoomIn').addEventListener('click',()=>{zoom=Math.min(4,zoom*1.2);applyZoom()});$('#fitView').addEventListener('click',fitView);window.addEventListener('resize',()=>{if(source){applyZoom();updateFocusRing()}});
    $('#exportScale').addEventListener('change',()=>updateExportDimensions(true));$('#exportWidth').addEventListener('input',()=>{if(!source)return;const w=Number($('#exportWidth').value)||1;$('#exportHeight').value=Math.max(1,Math.round(w*state.crop.height/state.crop.width));updateExportInfo()});$('#exportHeight').addEventListener('input',()=>{if(!source)return;const h=Number($('#exportHeight').value)||1;$('#exportWidth').value=Math.max(1,Math.round(h*state.crop.width/state.crop.height));updateExportInfo()});$('#exportFormat').addEventListener('change',()=>{syncExportVisibility();scheduleRecovery()});$('#transparentBg').addEventListener('change',()=>{syncExportVisibility();scheduleRecovery()});$('#exportQuality').addEventListener('input',e=>{e.target.parentElement.querySelector('output').textContent=`${e.target.value}%`});['exportWidth','exportHeight','exportScale','exportQuality','backgroundColor'].forEach(id=>$(`#${id}`).addEventListener('change',scheduleRecovery));
    $('#exportBtn').addEventListener('click',exportImage);$('#exportTopBtn').addEventListener('click',exportImage);$('#saveProjectBtn').addEventListener('click',()=>saveGallery('project'));$('#saveTemplateBtn').addEventListener('click',()=>saveGallery('template'));document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')scheduleRecovery()});
  }

  async function init(){buildDynamicControls();bind();syncExportVisibility();history.reset(state);setEnabled(false);const launched=await galleryLaunch();if(!launched)await recoveryPrompt()}
  init();
}());
